target 'BlueIntent_Example' do
  
  platform :ios, '9.0'
  inhibit_all_warnings!
  use_frameworks! :linkage => :static
  
  pod 'BlueIntent', :path => '../BlueIntent.podspec'
  pod 'BlueIntent/Layout', :path => '../BlueIntent.podspec'
  pod 'BlueIntent/Crypto', :path => '../BlueIntent.podspec'
  pod 'BlueIntent/DB', :path => '../BlueIntent.podspec'
  pod 'BlueIntent/BezierPath', :path => '../BlueIntent.podspec'
  pod 'BlueIntent/ControllerTransitioning', :path => '../BlueIntent.podspec'
  pod 'BlueIntent/AppleLogin', :path => '../BlueIntent.podspec'

  target 'BlueIntent_Tests' do
    inherit! :search_paths
  end
  
end

target 'BlueIntent_Watch_Example WatchKit Extension' do
  
  platform :watchos, '6.0'
  inhibit_all_warnings!
  use_frameworks! :linkage => :static
  
  pod 'BlueIntent/Foundation', :path => '../BlueIntent.podspec'
  pod 'BlueIntent/UIKit', :path => '../BlueIntent.podspec'
  
end

target 'BlueIntent_BezierPath_Example' do
  
  platform :ios, '9.0'
  inhibit_all_warnings!
  use_frameworks! :linkage => :static
  
  pod 'BlueIntent/BezierPath', :path => '../BlueIntent.podspec'
  
end
