platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'BlueIntent_Example' do
  pod 'BlueIntent', :path => '../BlueIntent.podspec'

  target 'BlueIntent_Tests' do
    inherit! :search_paths
  end
  
end
