platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks! :linkage => :static

target 'BlueIntent_Example' do
  pod 'BlueIntent', :path => '../BlueIntent.podspec'
  pod 'BlueIntent/Layout', :path => '../BlueIntent.podspec'
  pod 'BlueIntent/Crypto', :path => '../BlueIntent.podspec'

  target 'BlueIntent_Tests' do
    inherit! :search_paths
  end
  
end
